# Generated by Django 4.1.4 on 2023-01-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='embebe_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
